- name: Install CoreOS on ESXI HW
  collections:
  - name: community.vmware
  tasks:
  - name: Deploy Virtual Machine from OVF template in content library
    community.vmware.vmware_content_deploy_ovf_template:
      hostname: ''
      username: 'root'
      password: '{{ vcenter_password }}'
      ovf_template: rhel_test_template
      datastore: datastore1
      folder: vm
      datacenter: ha-datacenter
      name: coreos
    delegate_to: localhost